# bake
[recipes.default] #默认编译配置，会在不提供配置名时默认执行
# 必要参数
entrance="./" #编译入口，此处指定为当前目录
# 非必要参数
desc="Default Recipe"
output="./bin" #编译输出目录
all_platform.all_arch.replace.text."google" = "apple" #替换代码文件内容
#|___平台___||__架构__||__操作__||_操作子项_|


[recipes.my_recipe]
entrance="./"
output="./my_bin"
pairs = ["windows/386"] #编译darwin/arm64和windows/386
#all_platform.all_arch.docker.host="local"
#darwin.arm64.docker.host="local"
#darwin.arm64.output.path="hello/iam_darwin_arm64"
#darwin.arm64.docker.container="2a7c6546eea74b"
#darwin.arm64.docker.image="golang"
#all_platform.all_arch.docker.container="2a7c6546eea74b"

[recipes.release]
entrance="./"
desc="Release"
output="./release"